export const hoodieShipping = {
  // Europe
  FR: {
    name: "France",
    delivery: "2-5 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  GB: {
    name: "Royaume-Uni",
    delivery: "2-4 jours ouvrables",
    basePrice: 5.99,
    additionalPrice: 2.0,
  },
  DE: {
    name: "Allemagne",
    delivery: "3-3 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  AD: {
    name: "Andorre",
    delivery: "3-4 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  AL: {
    name: "Albanie",
    delivery: "7-13 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  AM: {
    name: "Arménie",
    delivery: "7-21 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  AT: {
    name: "Autriche",
    delivery: "2-6 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  AZ: {
    name: "Azerbaïdjan",
    delivery: "7-14 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  BE: {
    name: "Belgique",
    delivery: "2-3 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  BA: {
    name: "Bosnie-Herzégovine",
    delivery: "7-21 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  BG: {
    name: "Bulgarie",
    delivery: "4-5 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  CY: {
    name: "Chypre",
    delivery: "3-7 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  VA: {
    name: "Cité du Vatican",
    delivery: "7-9 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  HR: {
    name: "Croatie",
    delivery: "3-4 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  DK: {
    name: "Danemark",
    delivery: "2-6 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  ES: {
    name: "Espagne",
    delivery: "1-2 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  EE: {
    name: "Estonie",
    delivery: "3-3 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  FI: {
    name: "Finlande",
    delivery: "2-6 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  GE: {
    name: "Géorgie",
    delivery: "6-14 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  GI: {
    name: "Gibraltar",
    delivery: "7-14 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  GR: {
    name: "Grèce",
    delivery: "5-7 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  GG: {
    name: "Guernesey",
    delivery: "10-25 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  HU: {
    name: "Hongrie",
    delivery: "3-4 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  IM: {
    name: "Île de Man",
    delivery: "10-14 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  FO: {
    name: "Îles Féroé",
    delivery: "7-14 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  IE: {
    name: "Irlande",
    delivery: "2-6 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  IS: {
    name: "Islande",
    delivery: "7-9 jours ouvrables",
    basePrice: 9.99,
    additionalPrice: 2.0,
  },
  IT: {
    name: "Italie",
    delivery: "2-4 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  JE: {
    name: "Jersey",
    delivery: "10-14 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  KZ: {
    name: "Kazakhstan",
    delivery: "6-10 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  XK: {
    name: "Kosovo",
    delivery: "7-21 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  LV: {
    name: "Lettonie",
    delivery: "1-1 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  LI: {
    name: "Liechtenstein",
    delivery: "5-7 jours ouvrables",
    basePrice: 9.99,
    additionalPrice: 2.0,
  },
  LT: {
    name: "Lituanie",
    delivery: "2-3 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  LU: {
    name: "Luxembourg",
    delivery: "2-6 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  MK: {
    name: "Macédoine du Nord",
    delivery: "6-14 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  MT: {
    name: "Malte",
    delivery: "3-7 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  MD: {
    name: "Moldavie",
    delivery: "7-21 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  MC: {
    name: "Monaco",
    delivery: "7-14 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  ME: {
    name: "Monténégro",
    delivery: "7-21 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  NO: {
    name: "Norvège",
    delivery: "2-6 jours ouvrables",
    basePrice: 9.99,
    additionalPrice: 2.0,
  },
  NL: {
    name: "Pays-Bas",
    delivery: "1-3 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  PL: {
    name: "Pologne",
    delivery: "3-7 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  PT: {
    name: "Portugal",
    delivery: "2-6 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  CZ: {
    name: "République tchèque",
    delivery: "2-6 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  RO: {
    name: "Roumanie",
    delivery: "4-6 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  SM: {
    name: "Saint-Marin",
    delivery: "7-14 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  RS: {
    name: "Serbie",
    delivery: "8-14 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  SK: {
    name: "Slovaquie",
    delivery: "2-3 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  SI: {
    name: "Slovénie",
    delivery: "2-3 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  SE: {
    name: "Suède",
    delivery: "3-4 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  CH: {
    name: "Suisse",
    delivery: "3-7 jours ouvrables",
    basePrice: 9.99,
    additionalPrice: 2.0,
  },
  SJ: {
    name: "Svalbard et Jan Mayen",
    delivery: "10-25 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },
  UA: {
    name: "Ukraine",
    delivery: "6-15 jours ouvrables",
    basePrice: 6.29,
    additionalPrice: 2.0,
  },

  // Amériques
  US: {
    name: "États-Unis",
    delivery: "3-6 jours ouvrables",
    basePrice: 8.09,
    additionalPrice: 2.2,
  },
  BR: {
    name: "Brésil",
    delivery: "3-5 jours ouvrables",
    basePrice: 5.39,
    additionalPrice: 2.7,
  },
  CA: {
    name: "Canada",
    delivery: "2-2 jours ouvrables",
    basePrice: 9.49,
    additionalPrice: 2.05,
  },
  AI: {
    name: "Anguilla",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  AG: {
    name: "Antigua-et-Barbuda",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  AR: {
    name: "Argentine",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  AW: {
    name: "Aruba",
    delivery: "3-5 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  BS: {
    name: "Bahamas",
    delivery: "6-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  BB: {
    name: "Barbade",
    delivery: "2-4 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  BZ: {
    name: "Belize",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  BM: {
    name: "Bermudes",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  BO: {
    name: "Bolivie",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  CL: {
    name: "Chili",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  CO: {
    name: "Colombie",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  CR: {
    name: "Costa Rica",
    delivery: "4-6 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  CW: {
    name: "Curaçao",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  DM: {
    name: "Dominique",
    delivery: "6-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  GD: {
    name: "Grenade",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  GL: {
    name: "Groenland",
    delivery: "7-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  GP: {
    name: "Guadeloupe",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  GT: {
    name: "Guatemala",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  GY: {
    name: "Guyane",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  GF: {
    name: "Guyane française",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  HT: {
    name: "Haïti",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  HN: {
    name: "Honduras",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  JM: {
    name: "Jamaïque",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  MQ: {
    name: "Martinique",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  MX: {
    name: "Mexique",
    delivery: "3-6 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  MS: {
    name: "Montserrat",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  NI: {
    name: "Nicaragua",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  PA: {
    name: "Panama",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  PY: {
    name: "Paraguay",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  PE: {
    name: "Pérou",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  PR: {
    name: "Porto Rico",
    delivery: "5-9 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },

  // Asie-Pacifique
  JP: {
    name: "Japon",
    delivery: "2-4 jours ouvrables",
    basePrice: 5.99,
    additionalPrice: 2.0,
  },
  AU: {
    name: "Australie",
    delivery: "2-5 jours ouvrables",
    basePrice: 9.79,
    additionalPrice: 1.8,
  },
  NZ: {
    name: "Nouvelle-Zélande",
    delivery: "4-7 jours ouvrables",
    basePrice: 9.79,
    additionalPrice: 1.8,
  },
  CN: {
    name: "Chine",
    delivery: "4-7 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  HK: {
    name: "Hong Kong",
    delivery: "4-7 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  ID: {
    name: "Indonésie",
    delivery: "6-10 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  IN: {
    name: "Inde",
    delivery: "6-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  KR: {
    name: "Corée, République de",
    delivery: "7-7 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  MO: {
    name: "Macao",
    delivery: "6-10 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  MY: {
    name: "Malaisie",
    delivery: "6-10 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  MV: {
    name: "Maldives",
    delivery: "6-10 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  NP: {
    name: "Népal",
    delivery: "6-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  NC: {
    name: "Nouvelle-Calédonie",
    delivery: "10-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  PK: {
    name: "Pakistan",
    delivery: "6-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  PH: {
    name: "Philippines",
    delivery: "6-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  PF: {
    name: "Polynésie française",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  SG: {
    name: "Singapour",
    delivery: "6-10 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  LK: {
    name: "Sri Lanka",
    delivery: "6-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  TW: {
    name: "Taïwan",
    delivery: "8-8 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  TH: {
    name: "Thaïlande",
    delivery: "7-9 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  VN: {
    name: "Vietnam",
    delivery: "6-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },

  // Moyen-Orient
  BH: {
    name: "Bahreïn",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  AE: {
    name: "Émirats Arabes Unis",
    delivery: "10-20 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  IQ: {
    name: "Irak",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  IL: {
    name: "Israël",
    delivery: "4-7 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  JO: {
    name: "Jordanie",
    delivery: "8-11 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  KW: {
    name: "Koweït",
    delivery: "8-11 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  LB: {
    name: "Liban",
    delivery: "8-11 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  OM: {
    name: "Oman",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  QA: {
    name: "Qatar",
    delivery: "8-11 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  SA: {
    name: "Arabie Saoudite",
    delivery: "8-11 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },

  // Afrique
  ZA: {
    name: "Afrique du Sud",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  DZ: {
    name: "Algérie",
    delivery: "10-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  AO: {
    name: "Angola",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  BJ: {
    name: "Bénin",
    delivery: "6-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  BW: {
    name: "Botswana",
    delivery: "6-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  BF: {
    name: "Burkina Faso",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  BI: {
    name: "Burundi",
    delivery: "6-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  CM: {
    name: "Cameroun",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  CV: {
    name: "Cap-Vert",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  KM: {
    name: "Comores",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  CG: {
    name: "Congo",
    delivery: "5-7 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  CD: {
    name: "Congo, République Démocratique du",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  CI: {
    name: "Côte d'Ivoire",
    delivery: "2-4 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  DJ: {
    name: "Djibouti",
    delivery: "6-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  EG: {
    name: "Égypte",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  ER: {
    name: "Érythrée",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  SZ: {
    name: "Eswatini",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  ET: {
    name: "Éthiopie",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  GA: {
    name: "Gabon",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  GM: {
    name: "Gambie",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  GH: {
    name: "Ghana",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  GN: {
    name: "Guinée",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  GQ: {
    name: "Guinée Équatoriale",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  GW: {
    name: "Guinée-Bissau",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  KE: {
    name: "Kenya",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  LS: {
    name: "Lesotho",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  LR: {
    name: "Liberia",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  LY: {
    name: "Libye",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  MG: {
    name: "Madagascar",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  MW: {
    name: "Malawi",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  ML: {
    name: "Mali",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  MA: {
    name: "Maroc",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  MR: {
    name: "Mauritanie",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  MU: {
    name: "Île Maurice",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  YT: {
    name: "Mayotte",
    delivery: "5-20 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  MZ: {
    name: "Mozambique",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  NA: {
    name: "Namibie",
    delivery: "10-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  NE: {
    name: "Niger",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  NG: {
    name: "Nigeria",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  UG: {
    name: "Ouganda",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  RE: {
    name: "Réunion",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  RW: {
    name: "Rwanda",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  SN: {
    name: "Sénégal",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  SC: {
    name: "Seychelles",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  SL: {
    name: "Sierra Leone",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  SO: {
    name: "Somalie",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  SD: {
    name: "Soudan",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  TZ: {
    name: "Tanzanie",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  TD: {
    name: "Tchad",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  TG: {
    name: "Togo",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  TN: {
    name: "Tunisie",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  ZM: {
    name: "Zambie",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  ZW: {
    name: "Zimbabwe",
    delivery: "8-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },

  AQ: {
    name: "Antarctique",
    delivery: "5-20 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  GS: {
    name: "Géorgie du Sud-et-les îles Sandwich du Sud",
    delivery: "5-20 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  BV: {
    name: "Île Bouvet",
    delivery: "5-20 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  CX: {
    name: "Île Christmas",
    delivery: "5-20 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  NF: {
    name: "Île Norfolk",
    delivery: "5-20 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  CC: {
    name: "Îles Cocos (Keeling)",
    delivery: "5-20 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  CK: {
    name: "Îles Cook",
    delivery: "5-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  HM: {
    name: "Îles Heard-et-MacDonald",
    delivery: "5-20 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  FK: {
    name: "Îles Malouines",
    delivery: "10-25 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  MP: {
    name: "Îles Mariannes du Nord",
    delivery: "6-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  MH: {
    name: "Îles Marshall",
    delivery: "10-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  UM: {
    name: "Îles mineures éloignées des États-Unis",
    delivery: "10-25 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  PN: {
    name: "Îles Pitcairn",
    delivery: "5-20 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  SB: {
    name: "Îles Salomon",
    delivery: "10-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  TC: {
    name: "Îles Turques-et-Caïques",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  VG: {
    name: "Îles Vierges britanniques",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  VI: {
    name: "Îles Vierges des États-Unis",
    delivery: "6-14 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  PS: {
    name: "Territoires palestiniens occupés",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  TF: {
    name: "Terres australes et antarctiques françaises",
    delivery: "10-25 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  IO: {
    name: "Territoire britannique de l'océan Indien",
    delivery: "5-20 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  TK: {
    name: "Tokelau",
    delivery: "10-25 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  TO: {
    name: "Tonga",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  TV: {
    name: "Tuvalu",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  VU: {
    name: "Vanuatu",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
  WF: {
    name: "Wallis-et-Futuna",
    delivery: "7-21 jours ouvrables",
    basePrice: 14.99,
    additionalPrice: 7.05,
  },
};
