export const tshirtShipping = {
  // Premium Shipping Countries
  JP: {
    name: "Japon",
    delivery: "2-4 jours ouvrables",
    basePrice: 3.99, // Currently 5.99
    additionalPrice: 1.25, // Currently 2.00
  },
  BR: {
    name: "Brésil",
    delivery: "3-5 jours ouvrables",
    basePrice: 4.09, // Currently 5.39
    additionalPrice: 2.25, // Currently 2.70
  },

  GB: {
    name: "Royaume-Uni",
    delivery: "2-4 jours ouvrables",
    basePrice: 4.19, // Currently 5.99
    additionalPrice: 1.25, // Currently 2.00
  },

  // European Standard Rate Countries (€4.29 + €1.25)
  AL: {
    name: "Albanie",
    delivery: "7-13 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  DE: {
    name: "Allemagne",
    delivery: "3-3 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  AD: {
    name: "Andorre",
    delivery: "3-4 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  AM: {
    name: "Arménie",
    delivery: "7-21 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  AT: {
    name: "Autriche",
    delivery: "2-6 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  AZ: {
    name: "Azerbaïdjan",
    delivery: "7-14 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  BE: {
    name: "Belgique",
    delivery: "2-3 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  BA: {
    name: "Bosnie-Herzégovine",
    delivery: "7-21 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  BG: {
    name: "Bulgarie",
    delivery: "4-5 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  CY: {
    name: "Chypre",
    delivery: "3-7 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  VA: {
    name: "Cité du Vatican",
    delivery: "7-9 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  HR: {
    name: "Croatie",
    delivery: "3-4 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  DK: {
    name: "Danemark",
    delivery: "2-6 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  ES: {
    name: "Espagne",
    delivery: "1-2 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  EE: {
    name: "Estonie",
    delivery: "3-3 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  FI: {
    name: "Finlande",
    delivery: "2-6 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  FR: {
    name: "France",
    delivery: "2-5 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  GE: {
    name: "Géorgie",
    delivery: "6-14 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  GI: {
    name: "Gibraltar",
    delivery: "7-14 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  GR: {
    name: "Grèce",
    delivery: "5-7 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  GG: {
    name: "Guernesey",
    delivery: "10-25 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  HU: {
    name: "Hongrie",
    delivery: "3-4 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  IM: {
    name: "Île de Man",
    delivery: "10-14 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  FO: {
    name: "Îles Féroé",
    delivery: "7-14 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  IE: {
    name: "Irlande",
    delivery: "2-6 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  IT: {
    name: "Italie",
    delivery: "2-4 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  JE: {
    name: "Jersey",
    delivery: "10-14 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  KZ: {
    name: "Kazakhstan",
    delivery: "6-10 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  XK: {
    name: "Kosovo",
    delivery: "7-21 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  LV: {
    name: "Lettonie",
    delivery: "1-1 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  LT: {
    name: "Lituanie",
    delivery: "2-3 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  LU: {
    name: "Luxembourg",
    delivery: "2-6 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  MK: {
    name: "Macédoine du Nord",
    delivery: "6-14 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  MT: {
    name: "Malte",
    delivery: "3-7 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  MD: {
    name: "Moldavie",
    delivery: "7-21 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  MC: {
    name: "Monaco",
    delivery: "7-14 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  ME: {
    name: "Monténégro",
    delivery: "7-21 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  NL: {
    name: "Pays-Bas",
    delivery: "1-3 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  PL: {
    name: "Pologne",
    delivery: "3-7 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  PT: {
    name: "Portugal",
    delivery: "2-6 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  CZ: {
    name: "République tchèque",
    delivery: "2-6 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  RO: {
    name: "Roumanie",
    delivery: "4-6 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  SM: {
    name: "Saint-Marin",
    delivery: "7-14 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  RS: {
    name: "Serbie",
    delivery: "8-14 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  SK: {
    name: "Slovaquie",
    delivery: "2-3 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  SI: {
    name: "Slovénie",
    delivery: "2-3 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  SE: {
    name: "Suède",
    delivery: "3-4 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  SJ: {
    name: "Svalbard et Jan Mayen",
    delivery: "10-25 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },
  UA: {
    name: "Ukraine",
    delivery: "6-15 jours ouvrables",
    basePrice: 4.29,
    additionalPrice: 1.25,
  },

  US: {
    name: "États-Unis",
    delivery: "3-6 jours ouvrables",
    basePrice: 4.49, // Currently correct but including for completeness
    additionalPrice: 2.1, // Currently correct
  },

  AU: {
    name: "Australie",
    delivery: "2-5 jours ouvrables",
    basePrice: 6.19, // Currently 9.79
    additionalPrice: 1.15, // Currently 1.80
  },
  NZ: {
    name: "Nouvelle-Zélande",
    delivery: "4-7 jours ouvrables",
    basePrice: 6.19, // Currently 9.79
    additionalPrice: 1.15, // Currently 1.80
  },

  // Canada correction
  CA: {
    name: "Canada",
    delivery: "2-2 jours ouvrables",
    basePrice: 7.69, // Currently 9.49
    additionalPrice: 1.7, // Currently 2.05
  },

  // Nordic/Swiss rates correction
  IS: {
    name: "Islande",
    delivery: "7-9 jours ouvrables",
    basePrice: 8.99, // Currently correct
    additionalPrice: 1.0, // Currently correct
  },
  LI: {
    name: "Liechtenstein",
    delivery: "5-7 jours ouvrables",
    basePrice: 8.99, // Currently correct
    additionalPrice: 1.0, // Currently correct
  },
  NO: {
    name: "Norvège",
    delivery: "2-6 jours ouvrables",
    basePrice: 8.99, // Currently correct
    additionalPrice: 1.0, // Currently correct
  },
  CH: {
    name: "Suisse",
    delivery: "3-7 jours ouvrables",
    basePrice: 8.99, // Currently correct
    additionalPrice: 1.0, // Currently correct
  },

  ZA: {
    name: "Afrique du Sud",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  DZ: {
    name: "Algérie",
    delivery: "10-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  AO: {
    name: "Angola",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  AI: {
    name: "Anguilla",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  AQ: {
    name: "Antarctique",
    delivery: "5-20 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  AG: {
    name: "Antigua-et-Barbuda",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  SA: {
    name: "Arabie Saoudite",
    delivery: "8-11 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  AR: {
    name: "Argentine",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  AW: {
    name: "Aruba",
    delivery: "3-5 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  BS: {
    name: "Bahamas",
    delivery: "6-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  BH: {
    name: "Bahreïn",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  BD: {
    name: "Bangladesh",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  BB: {
    name: "Barbade",
    delivery: "2-4 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  BZ: {
    name: "Belize",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  BJ: {
    name: "Bénin",
    delivery: "6-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  BM: {
    name: "Bermudes",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  BO: {
    name: "Bolivie",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  BW: {
    name: "Botswana",
    delivery: "6-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  BN: {
    name: "Brunéi Darussalam",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  BF: {
    name: "Burkina Faso",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  BI: {
    name: "Burundi",
    delivery: "6-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  KH: {
    name: "Cambodge",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  CM: {
    name: "Cameroun",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  CV: {
    name: "Cap-Vert",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  CL: {
    name: "Chili",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  CN: {
    name: "Chine",
    delivery: "4-7 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  CO: {
    name: "Colombie",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  KM: {
    name: "Comores",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  CG: {
    name: "Congo",
    delivery: "5-7 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  CD: {
    name: "Congo, République Démocratique du",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  KR: {
    name: "Corée, République de",
    delivery: "7-7 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  CR: {
    name: "Costa Rica",
    delivery: "4-6 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  CI: {
    name: "Côte d'Ivoire",
    delivery: "2-4 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  CW: {
    name: "Curaçao",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  DJ: {
    name: "Djibouti",
    delivery: "6-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  DM: {
    name: "Dominique",
    delivery: "6-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  EG: {
    name: "Égypte",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  AE: {
    name: "Émirats Arabes Unis",
    delivery: "10-20 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  ER: {
    name: "Érythrée",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  SZ: {
    name: "Eswatini",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  ET: {
    name: "Éthiopie",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  FJ: {
    name: "Fidji",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  GA: {
    name: "Gabon",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  GM: {
    name: "Gambie",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  GS: {
    name: "Géorgie du Sud-et-les îles Sandwich du Sud",
    delivery: "5-20 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  GH: {
    name: "Ghana",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  GD: {
    name: "Grenade",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  GL: {
    name: "Groenland",
    delivery: "7-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  GP: {
    name: "Guadeloupe",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  GU: {
    name: "Guam",
    delivery: "10-25 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  GT: {
    name: "Guatemala",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  GN: {
    name: "Guinée",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  GQ: {
    name: "Guinée Équatoriale",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  GW: {
    name: "Guinée-Bissau",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  GY: {
    name: "Guyane",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  GF: {
    name: "Guyane française",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  HT: {
    name: "Haïti",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  HN: {
    name: "Honduras",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  HK: {
    name: "Hong Kong",
    delivery: "4-7 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  BV: {
    name: "Île Bouvet",
    delivery: "5-20 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  CX: {
    name: "Île Christmas",
    delivery: "5-20 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  MU: {
    name: "Île Maurice",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  NF: {
    name: "Île Norfolk",
    delivery: "5-20 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  KY: {
    name: "Îles Caïmans",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  CC: {
    name: "Îles Cocos (Keeling)",
    delivery: "5-20 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  CK: {
    name: "Îles Cook",
    delivery: "5-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  HM: {
    name: "Îles Heard-et-MacDonald",
    delivery: "5-20 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  FK: {
    name: "Îles Malouines",
    delivery: "10-25 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  MP: {
    name: "Îles Mariannes du Nord",
    delivery: "6-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  MH: {
    name: "Îles Marshall",
    delivery: "10-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  UM: {
    name: "Îles mineures éloignées des États-Unis",
    delivery: "10-25 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  PN: {
    name: "Îles Pitcairn",
    delivery: "5-20 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  SB: {
    name: "Îles Salomon",
    delivery: "10-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  TC: {
    name: "Îles Turques-et-Caïques",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  VG: {
    name: "Îles Vierges britanniques",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  VI: {
    name: "Îles Vierges des États-Unis",
    delivery: "6-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  IN: {
    name: "Inde",
    delivery: "6-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  ID: {
    name: "Indonésie",
    delivery: "6-10 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  IQ: {
    name: "Irak",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  IR: {
    name: "Iran",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  IL: {
    name: "Israël",
    delivery: "4-7 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  JM: {
    name: "Jamaïque",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  JO: {
    name: "Jordanie",
    delivery: "8-11 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  KE: {
    name: "Kenya",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  KG: {
    name: "Kirghizistan",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  KI: {
    name: "Kiribati",
    delivery: "10-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  KW: {
    name: "Koweït",
    delivery: "8-11 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  LS: {
    name: "Lesotho",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  LB: {
    name: "Liban",
    delivery: "8-11 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  LR: {
    name: "Liberia",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  MO: {
    name: "Macao",
    delivery: "6-10 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  MG: {
    name: "Madagascar",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  MY: {
    name: "Malaisie",
    delivery: "6-10 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  MW: {
    name: "Malawi",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  MV: {
    name: "Maldives",
    delivery: "6-10 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  ML: {
    name: "Mali",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  MA: {
    name: "Maroc",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  MQ: {
    name: "Martinique",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  MR: {
    name: "Mauritanie",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  YT: {
    name: "Mayotte",
    delivery: "5-20 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  MX: {
    name: "Mexique",
    delivery: "3-6 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  FM: {
    name: "Micronésie, États fédérés de",
    delivery: "10-20 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  MS: {
    name: "Montserrat",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  MZ: {
    name: "Mozambique",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  MM: {
    name: "Myanmar",
    delivery: "10-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  NA: {
    name: "Namibie",
    delivery: "10-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  NR: {
    name: "Nauru",
    delivery: "10-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  NP: {
    name: "Népal",
    delivery: "6-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  NI: {
    name: "Nicaragua",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  NE: {
    name: "Niger",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  NG: {
    name: "Nigeria",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  NU: {
    name: "Niue",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  NC: {
    name: "Nouvelle-Calédonie",
    delivery: "10-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  OM: {
    name: "Oman",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  UG: {
    name: "Ouganda",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  UZ: {
    name: "Ouzbékistan",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  PK: {
    name: "Pakistan",
    delivery: "6-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  PW: {
    name: "Palaos",
    delivery: "10-20 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  PA: {
    name: "Panama",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  PG: {
    name: "Papouasie-Nouvelle-Guinée",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  PY: {
    name: "Paraguay",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  PE: {
    name: "Pérou",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  PH: {
    name: "Philippines",
    delivery: "6-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  PF: {
    name: "Polynésie française",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  PR: {
    name: "Porto Rico",
    delivery: "5-9 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  QA: {
    name: "Qatar",
    delivery: "8-11 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  CF: {
    name: "République centrafricaine",
    delivery: "6-12 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  DO: {
    name: "République Dominicaine",
    delivery: "6-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  RE: {
    name: "Réunion",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  RW: {
    name: "Rwanda",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  EH: {
    name: "Sahara occidental",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  KN: {
    name: "Saint-Christophe-et-Niévès",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  MF: {
    name: "Saint-Martin",
    delivery: "5-20 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  PM: {
    name: "Saint-Pierre-et-Miquelon",
    delivery: "5-20 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  VC: {
    name: "Saint-Vincent-et-les-Grenadines",
    delivery: "6-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  SH: {
    name: "Sainte-Hélène",
    delivery: "5-20 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  LC: {
    name: "Sainte-Lucie",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  SV: {
    name: "Salvador",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  WS: {
    name: "Samoa américaines",
    delivery: "6-7 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  ST: {
    name: "Sao Tomé-et-Principe",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  SN: {
    name: "Sénégal",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  SC: {
    name: "Seychelles",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  SL: {
    name: "Sierra Leone",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  SG: {
    name: "Singapour",
    delivery: "6-10 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  SO: {
    name: "Somalie",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  SD: {
    name: "Soudan",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  LK: {
    name: "Sri Lanka",
    delivery: "6-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  SR: {
    name: "Suriname",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  TJ: {
    name: "Tadjikistan",
    delivery: "8-11 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  TW: {
    name: "Taïwan",
    delivery: "8-8 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  TZ: {
    name: "Tanzanie",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  TF: {
    name: "Terres australes et antarctiques françaises",
    delivery: "10-25 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  IO: {
    name: "Territoire britannique de l'océan Indien",
    delivery: "5-20 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  PS: {
    name: "Territoires palestiniens occupés",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  TH: {
    name: "Thaïlande",
    delivery: "7-9 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  TG: {
    name: "Togo",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  TK: {
    name: "Tokelau",
    delivery: "10-25 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  TO: {
    name: "Tonga",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  TT: {
    name: "Trinité-et-Tobago",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  TN: {
    name: "Tunisie",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  TM: {
    name: "Turkménistan",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  TR: {
    name: "Turquie",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  TV: {
    name: "Tuvalu",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  UY: {
    name: "Uruguay",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  VU: {
    name: "Vanuatu",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  VE: {
    name: "Venezuela",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  VN: {
    name: "Vietnam",
    delivery: "6-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  WF: {
    name: "Wallis-et-Futuna",
    delivery: "7-21 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  ZM: {
    name: "Zambie",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
  ZW: {
    name: "Zimbabwe",
    delivery: "8-14 jours ouvrables",
    basePrice: 10.59,
    additionalPrice: 5.3,
  },
};
